import { flatHeadScrewModelPropsSchema } from "@tscircuit/modelprinter"
import { FlatHeadScrew } from "jscad-electronics"
import type { ModelAdapter } from "./types"

export const adapter = {
  name: "Flat head screw",
  category: "Fasteners",
  description:
    "Configure and preview a flat head screw using the upstream model dimensions.",
  tags: ["flatheadscrew", "fasteners"],
  spec: "flatheadscrew_m4_l10mm_hexsocket_nothreads",
  componentName: "FlatHeadScrew",
  schema: flatHeadScrewModelPropsSchema,
  component: FlatHeadScrew,
  lengths: {
    length: "l",
    diameter: "diameter",
    threadPitch: "threadpitch",
    headDiameter: "headdiameter",
    headHeight: "headheight",
    socketAcrossFlats: "socketacrossflats",
    socketDepth: "socketdepth",
    underHeadRadius: "underheadradius",
    maximumThreadLength: "maximumthreadlength",
    tipChamfer: "tipchamfer",
    threadRootDiameter: "threadrootdiameter",
    threadPitchDiameter: "threadpitchdiameter",
  },
  numbers: {
    headAngle: "headangle",
    tipChamferAngle: "tipchamferangle",
    threadFlankAngle: "threadflankangle",
  },
  selectors: {
    standard: "standard",
    thread: "thread",
    drive: "drive",
    threadHand: "threadhand",
    threadClass: "threadclass",
    threadGender: "threadgender",
  },
  flags: {
    drive: { hexsocket: "hexsocket" },
    thread: { full: "fullthread" },
    threadHand: { left: "lefthanded", right: "" },
    threadGender: { male: "" },
  },
  booleans: { showThreads: ["threads", "nothreads"] },
  aliases: {
    m: "metricSize",
    metricsize: "metricSize",
    l: "length",
    length: "length",
    standard: "standard",
    thread: "thread",
    drive: "drive",
    threadhand: "threadHand",
    threadclass: "threadClass",
    threadgender: "threadGender",
    diameter: "diameter",
    threadpitch: "threadPitch",
    headdiameter: "headDiameter",
    headheight: "headHeight",
    socketacrossflats: "socketAcrossFlats",
    socketdepth: "socketDepth",
    underheadradius: "underHeadRadius",
    maximumthreadlength: "maximumThreadLength",
    headangle: "headAngle",
    tipchamferangle: "tipChamferAngle",
    threadflankangle: "threadFlankAngle",
    tipchamfer: "tipChamfer",
    threadrootdiameter: "threadRootDiameter",
    threadpitchdiameter: "threadPitchDiameter",
    d: "diameter",
    headh: "headHeight",
    headd: "headDiameter",
    socketaf: "socketAcrossFlats",
    socketh: "socketDepth",
  },
} satisfies ModelAdapter
