import { panScrewModelPropsSchema } from "@tscircuit/modelprinter"
import { PanScrew } from "jscad-electronics"
import type { ModelAdapter } from "./types"

export const adapter = {
  name: "Pan head screw",
  category: "Fasteners",
  description:
    "Configure and preview a pan head screw using the upstream model dimensions.",
  tags: ["panscrew", "fasteners"],
  spec: "panscrew_m4_l10mm_phillips_nothreads",
  componentName: "PanScrew",
  schema: panScrewModelPropsSchema,
  component: PanScrew,
  lengths: {
    length: "l",
    diameter: "diameter",
    threadPitch: "threadpitch",
    headDiameter: "headdiameter",
    headHeight: "headheight",
    crownRadius: "crownradius",
    underHeadRadius: "underheadradius",
    recessReferenceDiameter: "recessreferencediameter",
    recessPenetration: "recesspenetration",
    maximumThreadLength: "maximumthreadlength",
    tipChamfer: "tipchamfer",
    threadRootDiameter: "threadrootdiameter",
    threadPitchDiameter: "threadpitchdiameter",
    recessB: "recessb",
    recessE: "recesse",
    recessG: "recessg",
    recessF: "recessf",
    recessRadius: "recessradius",
    recessT1: "recesst1",
    recessReferencePlaneHeight: "recessreferenceplaneheight",
  },
  numbers: {
    recessNumber: "recessnumber",
    tipChamferAngle: "tipchamferangle",
    threadFlankAngle: "threadflankangle",
    recessAlpha: "recessalpha",
    recessBeta: "recessbeta",
    recessOuterWingAngle: "recessouterwingangle",
    recessInnerWingAngle: "recessinnerwingangle",
  },
  selectors: {
    standard: "standard",
    thread: "thread",
    drive: "drive",
    threadHand: "threadhand",
    threadClass: "threadclass",
    threadGender: "threadgender",
  },
  flags: {
    drive: { phillips: "phillips" },
    thread: { full: "fullthread" },
    threadHand: { left: "lefthanded", right: "" },
    threadGender: { male: "" },
  },
  booleans: { showThreads: ["threads", "nothreads"] },
  aliases: {
    m: "metricSize",
    metricsize: "metricSize",
    l: "length",
    length: "length",
    standard: "standard",
    thread: "thread",
    drive: "drive",
    threadhand: "threadHand",
    threadclass: "threadClass",
    threadgender: "threadGender",
    diameter: "diameter",
    threadpitch: "threadPitch",
    headdiameter: "headDiameter",
    headheight: "headHeight",
    crownradius: "crownRadius",
    underheadradius: "underHeadRadius",
    recessnumber: "recessNumber",
    recessreferencediameter: "recessReferenceDiameter",
    recesspenetration: "recessPenetration",
    maximumthreadlength: "maximumThreadLength",
    tipchamferangle: "tipChamferAngle",
    threadflankangle: "threadFlankAngle",
    tipchamfer: "tipChamfer",
    threadrootdiameter: "threadRootDiameter",
    threadpitchdiameter: "threadPitchDiameter",
    recessb: "recessB",
    recesse: "recessE",
    recessg: "recessG",
    recessf: "recessF",
    recessradius: "recessRadius",
    recesst1: "recessT1",
    recessalpha: "recessAlpha",
    recessbeta: "recessBeta",
    recessouterwingangle: "recessOuterWingAngle",
    recessinnerwingangle: "recessInnerWingAngle",
    recessreferenceplaneheight: "recessReferencePlaneHeight",
    d: "diameter",
    headh: "headHeight",
    headd: "headDiameter",
  },
} satisfies ModelAdapter
